.Dd January 31, 2014
.Dt evtxinfo
.Os libevtx
.Sh NAME
.Nm evtxinfo
.Nd determines information about a Windows XML EventViewer Log (EVTX) file
.Sh SYNOPSIS
.Nm evtxinfo
.Op Fl c Ar codepage
.Op Fl hvV
.Va Ar source
.Sh DESCRIPTION
.Nm evtxinfo
is a utility to determine information about a Windows XML EventViewer Log (EVTX) file
.Pp
.Nm evtxinfo
is part of the
.Nm libevtx
package.
.Nm libevtx
is a library to accesss the Windows XML EventViewer Log (EVTX) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar codepage
specify the codepage of ASCII strings, options: ascii, windows-874, windows-932, windows-936, windows-949, windows-950, windows-1250, windows-1251, windows-1252 (default), windows-1253, windows-1254, windows-1255, windows-1256, windows-1257 or windows-1258
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
.Dl        ...

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libevtx/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (C) 2011-2017, Joachim Metz <joachim.metz@gmail.com>.
.Sh SEE ALSO
